version: '3.8'
services:
  api-server:
    container_name: bbit-api-server
    build: 
      context: ./api-server
      dockerfile: Dockerfile
    volumes:
      - ./api-server:/var/www/html/
    links:
     - db
    environment:
      BBIT_DB_HOST: ${BBIT_DB_HOST}
      BBIT_DB_USER: ${BBIT_DB_USER}
      BBIT_DB_PASSWORD: ${BBIT_DB_PASSWORD}
      BBIT_DB_NAME: ${BBIT_DB_NAME}
      BBIT_DB_PORT: ${BBIT_DB_PORT}
    ports:
      - 9000:80
    #command: bash -c "apt-get update && docker-php-ext-install mysqli && docker-php-ext-enable mysqli && apachectl restart"

  application:
    container_name: bbit-app
    image: php:8.0-apache
    volumes:
      - ./application:/var/www/html/
    ports:
      - 8000:80

  db:
    image: mysql:5.7
    container_name: bbit-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${BBIT_DB_NAME}
      MYSQL_USER: ${BBIT_DB_USER}
      MYSQL_PASSWORD: ${BBIT_DB_PASSWORD}
    ports:
      - "6033:3306"
    volumes:
      - /var/bbit/dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bbit-phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  dbdata: